version: '3.1'
services:
  gateway:
    image: inductiveautomation/ignition:latest  # You can change `latest` to a specific version, e.g. `8.0.5`
    restart: "unless-stopped"
    ports:
      - "1088:8088"     # Port 1088 is visable out side of the docker
    stop_grace_period: 30s
#    secrets:
#      - gateway-password
    volumes:
      # - ./gateway_backup.gwbk:/restore.gwbk
      - gateway_data_ignition_test2:/var/lib/ignition/data
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
#    env_file: ignition.env  # optionally specify variables in a file, or using `environment:` below
    environment:
      TZ: Europe/Oslo
    networks:
      - ignition-test2-Storm-network
  db:
    image: mariadb:latest
    restart: "unless-stopped"
    ports:
      # Note that the 3306 port doesn't need to be published here for the gateway container to connect, 
      # only for external connectivity to the database.
      - "1306:3306"         # Port 1088 is visable out side of the docker
    volumes:
     - db_data_ignition_test2:/var/lib/mysql
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      MARIADB_ROOT_PASSWORD: ignition    # specify the password for the root user
      MARIADB_DATABASE: ignition         # create a database with this name
      MARIADB_USER: ignition             # create a user with this name, with all privileges on MARIADB_DATABASE if specified
      MARIADB_PASSWORD: ignition         # password for above user
    networks:
      - ignition-test2-Storm-network
networks:
  ignition-test2-Storm-network:

volumes:
  gateway_data_ignition_test2:
  db_data_ignition_test2: